= Controller

Each entity (except <<department-manager>>) has it's own controller, mapped to the corresponding path. Depending on the entity, it is also possible
to pass parameters to access to a specific information (for example, the detailed view of an employee passing his
employee number).

[#departments-controller]
== Departments Controller

=== Path: "/departments"
Returns the complete list of departments, ordered by the department number. Each department entry contains the same
information as in the entity <<#department>>.

=== Path: "/departments/{id}"
Returns the following information corresponding to the department number _id_:

* The data contained in <<#department>>. In the root.
* Information about the current and past managers. Key _managers_.
** Based in <<#employee>>:
*** Employee number
*** First name
*** Last name
** Based in <<#department-manager>>:
*** From date
*** To date

=== Path: "/departments/{id}/employees"
This path accepts two parameters for paginating the result:

* _start_: sets the first employee number based in the limit that the list will contain (default value 0).
* _limit_: sets the number of results to be retrieved (default value 20, max value 100).

Returns the following information corresponding to the employees of the department number _id_:

* A list of employees, which contains the following information:
** Based in <<#employee>>:
*** Employee number
*** First name
*** Last name
** Based in <<#department-employee>>:
*** From date
*** To date

The header contains a _X-Total-Count_ value with the total number of employees.

[#employees-controller]
== Employees Controller

=== Path: "/employees"
This path accepts two parameters for paginating the result:

* _start_: sets the first employee number based in the limit that the list will contain (default value 0).
* _limit_: sets the number of results to be retrieved (default value 50, max value 100).

Returns a list of employees, in which each entry contains the same information as in the entity <<#employee>>.

=== Path: "/employees/{id}"
Returns the following information corresponding to the employee number _id_:

* The data contained in <<#employee>>, and more specifically in the following cases:
* If the employee is or has been a manager, information about the department and dates. Key _managerOf_.
** Based in <<#department>>:
*** Department number
*** Department name
** Based in <<#department-manager>>:
*** From date
*** To date
* Information about the department and dates where the employee has worked. Key _employeeOf_.
** Based in <<#department>>:
*** Department number
*** Department name
** Based in <<#department-manager>>:
*** From date
*** To date
* Information about the titles that the employee has currently or had in the past. Key _titles_.
** Title
** From date
** To date

[NOTE]
====
Only if the user has enough permissions:

* Information about the salaries that the employee has currently or had in the past. Key _salaries_.
** Salary
** From date
** To date
====