=== Controller

Each entity (except <<Model.adoc#department-manager>>) has it's own controller, mapped to the corresponding path. Depending on the entity, it is also possible
to pass parameters to access to a specific information (for example, the detailed view of an employee passing his
employee number).

[#departments-controller]
==== Departments Controller

* Path: "/departments"
+
Returns the complete list of departments. Each department entry contains the same information as in the entity
<<#department>>.

* Path: "/departments/{id}"
+
Returns the following information corresponding to the department number _id_:

** The data contained in <<#department>>. In the root.
** Information about the current and past managers. Key _managers_.
*** Based in <<#employee>>:
**** Employee number
**** First name
**** Last name
*** Based in <<#department-manager>>:
**** From date
**** To date
** A paginated list of employees, with the key _employees_ Contains the information:
*** Based in <<#employee>>:
**** Employee number
**** First name
**** Last name
*** Based in <<#department-employee>>:
**** From date
**** To date

[#employees-controller]
==== Employees Controller

* Path: "/employees"
+
Returns a list of employees, setting a default _start_ and _limit_ value, if not provided. Each employee entry contains the same information
as in the entity <<#employee>>.

* Path: "/employees/{id}"
+
Returns the following information corresponding to the employee number _id_:

** The data contained in <<#employee>>, and more specifically in the following cases:
** If the employee is or has been a manager, information about the department and dates. Key _managerOf_.
*** Based in <<#department>>:
**** Department number
**** Department name
*** Based in <<#department-manager>>:
**** From date
**** To date
** Information about the department and dates where the employee has worked. Key _employeeOf_.
*** Based in <<#department>>:
**** Department number
**** Department name
*** Based in <<#department-manager>>:
**** From date
**** To date
** Information about the titles that the employee has currently or had in the past. Key _titles_.
*** Title
*** From date
*** To date

[NOTE]
====
Only if the user has enough permissions:

** Information about the salaries that the employee has currently or had in the past. Key _salaries_.
*** Salary
*** From date
*** To date
====
